### PR TITLE
Add normalization and duplicates support

### PR DESCRIPTION
**Pull request by therealjumbo**
### Summary
This PR adds normalization function to the library. That is, in a json file that mixes multiple separators like `_` and `.`, you can normalize all of them to only `_`. In addition, if a file mixes a flattened style with an un-flattened style, that can also be normalized. In order to support normalization, duplicate detection was added to the flatten function in the event of a duplicate.

### Bug Fixes/New Features
* `normalize` function
* added "duplicate detection" in `flatten`

### How to Verify
I added unit tests to test this new functionality, I can add more if you feel that would be helpful. I also used it on our own json dictionaries of ~1500 lines with great results. 

### Side Effects
For the normalize function, several of the parameters should be required, but this means that I need to put them before the named/optional parameters. I left the ordering of the params in the existing functions unchanged, but that means the ordering of the params isn't consistent between `normalize` and `flatten` for the params that they share. 

### Resolves
No open issue or bug is resolved by this PR.

### Tests
All tests are currently passing. 
Tests added:
* `test_normalize_with_one_key`
* `test_normalize_with_mult_keys`
* `test_normalize_with_dupes`
* `test_normalize_expd_with_dupes`
Tests changed:
* None
### Code Reviewer(s)
@amir-ziai-zefr is this a feature you'd be interested in merging?

### CODE REVIEW

**Comment by therealjumbo** [comment]
I guess the CI is failing. I'll try to troubleshoot that. It worked locally...

**Comment by therealjumbo** [comment]
Ok, the duplicates needed to be sorted before comparing them in the unit test. I wonder if I should sort them before I return from flatten/normalize instead of relying on the caller to sort?

**Comment by amirziai** [comment]
Hey @therealjumbo. The changes looks very interesting. Do you mind updating the `README` to reference the use case(s) that lead you to these changes and maybe an example? Think it would be really helpful. Thanks!

**Comment by therealjumbo** [comment]
@amirziai 
I'll update the `README`.
I think I also should:
* add a unit test to raise that exception
* move the sorting of dupes into flattten

I'll reply to this thread when I think it's ready. Thanks for your time.

**Comment by amirziai** [comment]
hey @therealjumbo are you still working on this?

**Pull request closed without merging**
