### PR TITLE
update unflatten for NaNs, and add function flatten_preserve_lists

### LINKED ISSUE #40: unflatten from pandas dataframe
My use case is the following: I convert a json string in below form to a pandas dataframe. Pandas will automatically fill columns with NaN's if they are not defined for a particular record (as in below example). 

```
import pandas as pd, json
from flatten_json import flatten, unflatten

input = json.loads(""" 

[{
    "cola": {"colb": null, "colc": 10},          
    "cold": "hi"    
},
{
    "cola": null, 
    "cold": "hi"    
}]
""")


flat_json = [flatten(record, '.') for record in input]
df_flat = pd.DataFrame(flat_json)
```

when I try to unflatten the dataframe records, unflatten throws an error.

```
[unflatten(record, '.') for record in df_flat.to_dict('records')]
```

TypeError: 'float' object does not support item assignment

Hope you would agree that this is a fairly common use case, so would warrant a fix.

My proposal:

in flatten_json.py, function unflatten, I would change:
```
for item in flat_dict:
       _unflatten(unflattened_dict, item.split(separator), flat_dict[item])
```
with
```
list_keys = sorted(flat_dict.keys())
for i, item in enumerate(list_keys):
	if i != len(list_keys)-1:
		if not list_keys[i+1].startswith(list_keys[i]):
			_unflatten(unflattened_dict, item.split(separator), flat_dict[item])
		else:
			pass  # if key contained in next key, json will be invalid.
	else:
		#  last element
		_unflatten(unflattened_dict, item.split(separator), flat_dict[item])

```

### LINKED ISSUE #43: new function flatten_preserve_lists to limit flattening and preserve list structure
I propose to add a new function called flatten_preserve_list.

It would create a new record for every element in a list, akin to a left join between two tables in sql. It adds options max_list_index, which controls how many list indices are processed, and max_depth, which controls how many recursions are permitted. Given that the result of this function may be very large, these options help reduce output size and can be used for quick data investigation.

This function requires import of copy, re, and math libraries.

See below for the pull request. It works, but still contains some debug statement which I will remove if it is accepted.

### PR DESCRIPTION
**Pull request by kaiaeberli**
### Summary
The pull request changes the `unflatten` implementation, so that it can unflatten json that contains NaN  values. Such json is created when json is flattened and  converted to a pandas DataFrame. The dataframe will interpolate missing column values with NaN. Upon unflattening, the function should take care to remove these NaNs again. This addresses issue #40 .

This pull request also introduces a new function, `flatten_preserve_lists`. The current `flatten` implementation collapses list structure so that everything becomes a single row. This implementation preserves list structure, collapsing only dictionaries.

It creates a new record for every element in a list, akin to a left join between two tables in SQL. It adds options max_list_index, which controls how many list indices are processed, and max_depth, which controls how many recursions are permitted. Given that the result of this function may be very large, these options help reduce output size and can be used for quick data investigation.

This function requires import of copy, re, and math libraries.
This addresses issue #43 .

### Bug Fixes/New Features
* change `unflatten` to consider NaN values correctly to undo pandas DataFrame interpolation of missing column values 
* introduce `flatten_preserve_lists`, to allow list structure to be preserved and only collapse dicts.
* `flatten_preserve_lists` also pulls up single child elements to the parent level to prevent unnecessary nesting.

### How to Verify
Added tests: 
* test_unflatten_with_df_issue40
* test_flatten_preserve_lists_issue43
* test_flatten_preserve_lists_issue43_nested

### Side Effects
None to my knowledge.

### Resolves
Fixes #40 
Fixes #43 

### Tests
Added tests: 
* test_unflatten_with_df_issue40
* test_flatten_preserve_lists_issue43
* test_flatten_preserve_lists_issue43_nested
All tests are passing.

### Code Reviewer(s)
@amirziai

### CODE REVIEW

**Comment by amirziai** [comment]
thanks for the PR @kaiaeberli ! 

can u follow the pull request [template](https://github.com/amirziai/flatten/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and add more context?

**Comment by kaiaeberli** [comment]
@amirziai: sure - updated the pull request

**Comment by amirziai** [comment]
@kaiaeberli this is awesome. i'll approve and merge. sorry it took me so long to get around to it.

it'd be great if you could create another PR with an updated readme to include `flatten_preserve_lists` and your improvement to `unflatten`. i'm sure others can benefit from this contribution.

great work!

**Comment by damtur** [comment]
So that you know this release broke our workflow since we relied on not including empty lists and dictionaries in output. In my optinion this should be marked as a new feature, not patch version in Semver. 
Thank you :)

**Comment by amirziai** [comment]
sorry about that @damtur , didn't think about the release carefully. hope that you can pin to the old version and have the workflow going again.

**Comment by damtur** [comment]
No problem @amirziai we have things working now. It's just a kind ask to pay more attention to SEMVER ;). Thank you so much! And also thank you for actually fixing this.

**Pull request merged**
